In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder



In [2]:
df = pd.read_csv('processed_Bullying_Ayman.csv')
df.drop(columns=df.columns[0], inplace=True)
df.head()

record Bullied_on_school_property_in_past_12_months   
0       3                                           No  \
1       6                                           No   
2      11                                           No   
3      23                                           No   
4      24                                           No   

  Bullied_not_on_school_property_in_past_12_months   
0                                               No  \
1                                               No   
2                                               No   
3                                               No   
4                                               No   

  Cyber_bullied_in_past_12_months  Custom_Age   Sex  Physically_attacked   
0                              No          14  Male                    0  \
1                              No          13  Male                    0   
2                              No          15  Male                    0   
3                             Yes          13  Male                    0   
4                              No          14  Male                    0   

   Physical_fighting       Felt_lonely Close_friends   
0                  0             Never     3 or more  \
1                  1             Never     3 or more   
2                  1             Never     3 or more   
3                  2  Most of the time     3 or more   
4                  2  Most of the time             2   

   Miss_school_no_permission Other_students_kind_and_helpful   
0                          0                       Sometimes  \
1                          0                Most of the time   
2                          3                Most of the time   
3                          0                          Rarely   
4                          0                          Always   

  Parents_understand_problems Most_of_the_time_or_always_felt_lonely   
0                      Always                                     No  \
1                      Always                                     No   
2                      Always                                     No   
3                      Always                                    Yes   
4                   Sometimes                                    Yes   

   Missed_classes_or_school_without_permission  body_level  engaged_in_a_fight  
0                                        False         1.0               False  
1                                        False         1.0                True  
2                                         True         1.0                True  
3                                        False         1.0                True  
4                                        False         3.0                True

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32938 entries, 0 to 32937
Data columns (total 17 columns):
 #   Column                                            Non-Null Count  Dtype  
---  ------                                            --------------  -----  
 0   record                                            32938 non-null  int64  
 1   Bullied_on_school_property_in_past_12_months      32938 non-null  object 
 2   Bullied_not_on_school_property_in_past_12_months  32938 non-null  object 
 3   Cyber_bullied_in_past_12_months                   32938 non-null  object 
 4   Custom_Age                                        32938 non-null  int64  
 5   Sex                                               32938 non-null  object 
 6   Physically_attacked                               32938 non-null  int64  
 7   Physical_fighting                                 32938 non-null  int64  
 8   Felt_lonely                                       32938 non-null  object 
 9   Close_friends    

In [4]:
#we will merge both 'bullyed not on school property' and 'cyberbullied' into one column named 'bull outside school'
#this column we will use as our bigger population dataset, which we will infer our insights from the smaller column 'bullied in school'


In [5]:
print(f"unique values for Felt_lonely column: \n{df['Felt_lonely'].unique()}")
#can be ordered by [Never, Rarely, Sometimes, Most of the time, Always]
Loneliness_list = ['Never', 'Rarely', 'Sometimes', 'Most of the time', 'Always']
df['Felt_lonely']=df['Felt_lonely'].apply(lambda x: Loneliness_list.index(str(x)))

df['Felt_lonely'].head()
#now the column Felt Lonely is correctly encoded

unique values for Felt_lonely column: 
['Never' 'Most of the time' 'Rarely' 'Sometimes' 'Always']


0    0
1    0
2    0
3    3
4    3
Name: Felt_lonely, dtype: int64

In [6]:
print(f"unique values for Close_friends column : \n{df['Close_friends'].unique()}")
#can be ordered by [0, 1, 2, 3 or more]
Close_friends_list = ['0', '1', '2', '3 or more']
df['Close_friends']=df['Close_friends'].apply(lambda x: Close_friends_list.index(str(x)))

df['Close_friends'].head()
#now the column Close_friends Lonely is correctly encoded

unique values for Close_friends column : 
['3 or more' '2' '0' '1']


0    3
1    3
2    3
3    3
4    2
Name: Close_friends, dtype: int64

In [7]:
print(f"unique values for Other_students_kind column : \n{df['Other_students_kind_and_helpful'].unique()}")
#can be ordered by ['Never','Rarely', 'Sometimes', 'Most of the time' , 'Always' ]

Other_students_kind_and_helpful_list = ['Never','Rarely', 'Sometimes', 'Most of the time' , 'Always' ]
df['Other_students_kind_and_helpful']=df['Other_students_kind_and_helpful'].apply(lambda x: Other_students_kind_and_helpful_list.index(str(x)))

df['Other_students_kind_and_helpful'].head()
#now the column Other_students_kind_and_helpful Lonely is correctly encoded



unique values for Other_students_kind column : 
['Sometimes' 'Most of the time' 'Rarely' 'Always' 'Never']


0    2
1    3
2    3
3    1
4    4
Name: Other_students_kind_and_helpful, dtype: int64

In [8]:
print(f"unique values for Parents_understand_problems column : \n{df['Parents_understand_problems'].unique()}")
#can be ordered by ['Never','Rarely', 'Sometimes', 'Most of the time' , 'Always' ]

Parents_understand_problems_list = ['Never','Rarely', 'Sometimes', 'Most of the time' , 'Always' ]
df['Parents_understand_problems']=df['Parents_understand_problems'].apply(lambda x: Parents_understand_problems_list.index(str(x)))

df['Parents_understand_problems'].head()
#now the column Parents_understand_problems Lonely is correctly encoded



unique values for Parents_understand_problems column : 
['Always' 'Sometimes' 'Rarely' 'Most of the time' 'Never']


0    4
1    4
2    4
3    4
4    2
Name: Parents_understand_problems, dtype: int64

In [9]:
df.loc[df['Most_of_the_time_or_always_felt_lonely'] == 'Yes', 'Most_of_the_time_or_always_felt_lonely'] = True
df.loc[df['Most_of_the_time_or_always_felt_lonely'] == 'No', 'Most_of_the_time_or_always_felt_lonely'] = False
df['Most_of_the_time_or_always_felt_lonely'] = df['Most_of_the_time_or_always_felt_lonely'].astype('bool')

encoderr = LabelEncoder()
df['Sex'] = encoderr.fit_transform(df['Sex'])
df['Sex'] = df['Sex'].astype('int64')

In [10]:
new_df = df.copy()
new_df['Age'] = new_df['Custom_Age']
new_df.drop(columns=['Custom_Age'])
new_df['Bullied_Outside_School'] = False*len(new_df)
new_df.loc[(new_df['Bullied_not_on_school_property_in_past_12_months']=='Yes') | (new_df['Cyber_bullied_in_past_12_months']=='Yes'), 'Bullied_Outside_School'] = True
new_df['Bullied_Outside_School'] = new_df['Bullied_Outside_School'].astype('bool')

new_df['Bullied_in_school'] = False*len(new_df)
new_df.loc[new_df['Bullied_on_school_property_in_past_12_months']=='Yes', 'Bullied_in_school'] = True
new_df['Bullied_in_school'] = new_df['Bullied_in_school'].astype('bool')


new_df.drop(columns=['Bullied_not_on_school_property_in_past_12_months', 'Cyber_bullied_in_past_12_months', 'Bullied_on_school_property_in_past_12_months'], inplace=True)

new_df.head()

record  Custom_Age  Sex  Physically_attacked  Physical_fighting   
0       3          14    1                    0                  0  \
1       6          13    1                    0                  1   
2      11          15    1                    0                  1   
3      23          13    1                    0                  2   
4      24          14    1                    0                  2   

   Felt_lonely  Close_friends  Miss_school_no_permission   
0            0              3                          0  \
1            0              3                          0   
2            0              3                          3   
3            3              3                          0   
4            3              2                          0   

   Other_students_kind_and_helpful  Parents_understand_problems   
0                                2                            4  \
1                                3                            4   
2                                3                            4   
3                                1                            4   
4                                4                            2   

   Most_of_the_time_or_always_felt_lonely   
0                                   False  \
1                                   False   
2                                   False   
3                                    True   
4                                    True   

   Missed_classes_or_school_without_permission  body_level   
0                                        False         1.0  \
1                                        False         1.0   
2                                         True         1.0   
3                                        False         1.0   
4                                        False         3.0   

   engaged_in_a_fight  Age  Bullied_Outside_School  Bullied_in_school  
0               False   14                   False              False  
1                True   13                   False              False  
2                True   15                   False              False  
3                True   13                    True              False  
4                True   14                   False              False

In [11]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
features = new_df.drop(columns=['Bullied_in_school','Bullied_Outside_School'])
target_smaller_population = new_df['Bullied_in_school']
target_bigger_population = new_df['Bullied_Outside_School']
X_train, X_test, y_train, y_test = train_test_split(features, target_smaller_population, test_size=0.3,random_state=109) # 70% training and 30% test

### Training the model and tuning hyperparameters

In [12]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf_linear = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf_linear.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf_linear.predict(X_test)

In [13]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Model Accuracy: how often is the classifier correct?
print("############################################# USING LINEAR KERNEL #####################################################")
print("Accuracy:",accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred))
print("classification_report:\n",classification_report(y_test, y_pred))

############################################# USING LINEAR KERNEL #####################################################
Accuracy: 0.7828374822910342
Confusion Matrix:
 [[7579  203]
 [1943  157]]
classification_report:
               precision    recall  f1-score   support

       False       0.80      0.97      0.88      7782
        True       0.44      0.07      0.13      2100

    accuracy                           0.78      9882
   macro avg       0.62      0.52      0.50      9882
weighted avg       0.72      0.78      0.72      9882



In [14]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf_poly= svm.SVC(kernel='poly') # Linear Kernel

#Train the model using the training sets
clf_poly.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf_poly.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Model Accuracy: how often is the classifier correct?
print("############################################# USING POLYNOMIAL KERNEL #####################################################")
print("Accuracy Using Polynomial Kernel:",accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred))
print("classification_report:\n",classification_report(y_test, y_pred))

############################################# USING POLYNOMIAL KERNEL #####################################################
Accuracy Using Polynomial Kernel: 0.7874924104432302
Confusion Matrix:
 [[7782    0]
 [2100    0]]
classification_report:
               precision    recall  f1-score   support

       False       0.79      1.00      0.88      7782
        True       0.00      0.00      0.00      2100

    accuracy                           0.79      9882
   macro avg       0.39      0.50      0.44      9882
weighted avg       0.62      0.79      0.69      9882



C:\Users\swak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\swak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\swak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

In [15]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf_rbf = svm.SVC(kernel='rbf') # Linear Kernel

#Train the model using the training sets
clf_rbf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf_rbf.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Model Accuracy: how often is the classifier correct?
print("############################################# USING RBF KERNEL #####################################################")
print("Accuracy Using Polynomial Kernel:",accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred))
print("classification_report:\n",classification_report(y_test, y_pred))

############################################# USING RBF KERNEL #####################################################
Accuracy Using Polynomial Kernel: 0.7874924104432302
Confusion Matrix:
 [[7782    0]
 [2100    0]]
classification_report:
               precision    recall  f1-score   support

       False       0.79      1.00      0.88      7782
        True       0.00      0.00      0.00      2100

    accuracy                           0.79      9882
   macro avg       0.39      0.50      0.44      9882
weighted avg       0.62      0.79      0.69      9882



C:\Users\swak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\swak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\swak\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

In [16]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf_sigmoid = svm.SVC(kernel='sigmoid') # Linear Kernel

#Train the model using the training sets
clf_sigmoid.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf_sigmoid.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Model Accuracy: how often is the classifier correct?
print("############################################# USING RBF KERNEL #####################################################")
print("Accuracy Using Polynomial Kernel:",accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred))
print("classification_report:\n",classification_report(y_test, y_pred))

############################################# USING RBF KERNEL #####################################################
Accuracy Using Polynomial Kernel: 0.6646427848613641
Confusion Matrix:
 [[6147 1635]
 [1679  421]]
classification_report:
               precision    recall  f1-score   support

       False       0.79      0.79      0.79      7782
        True       0.20      0.20      0.20      2100

    accuracy                           0.66      9882
   macro avg       0.50      0.50      0.50      9882
weighted avg       0.66      0.66      0.66      9882



### We will use the linear kernel, now try to infer on the larger population

In [17]:
X_infer_train, X_infer_test, y_infer_train, y_test = train_test_split(features, target_bigger_population, test_size=0.3,random_state=109) # 70% training and 30% test


y_infer = clf_linear.predict(X_infer_test)

# Model Accuracy: how often is the classifier correct?
print("############################################# INFERENTIAL RESULTS #####################################################")
print("Accuracy Using LINEAR Kernel:",accuracy_score(y_test, y_infer))
print("Confusion Matrix:\n",confusion_matrix(y_test, y_infer))
print("classification_report:\n",classification_report(y_test, y_infer))

############################################# INFERENTIAL RESULTS #####################################################
Accuracy Using LINEAR Kernel: 0.675571746609998
Confusion Matrix:
 [[6473  157]
 [3049  203]]
classification_report:
               precision    recall  f1-score   support

       False       0.68      0.98      0.80      6630
        True       0.56      0.06      0.11      3252

    accuracy                           0.68      9882
   macro avg       0.62      0.52      0.46      9882
weighted avg       0.64      0.68      0.57      9882



In [18]:
import pickle
pickle.dump(clf_linear, open('SVM_linear.pkl', "wb"))